# Generated by Django 4.0.4 on 2022-04-28 19:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre y Apellido')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefono')),
                ('mess', ckeditor.fields.RichTextField(verbose_name='Mensaje')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el ')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Ultima Actualizacion')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
