# Generated by Django 4.0.4 on 2022-04-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('image', models.ImageField(default='Null', upload_to='', verbose_name='Imagen')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('info', models.TextField(verbose_name='Informacion')),
                ('created_at', models.DateField(verbose_name='Creado el ')),
                ('updated_at', models.DateField(verbose_name='Ultima Actualizacion')),
            ],
        ),
    ]
