# Generated by Django 4.0.4 on 2022-04-25 20:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Creado el '),
        ),
        migrations.AlterField(
            model_name='services',
            name='info',
            field=ckeditor.fields.RichTextField(verbose_name='Informacion'),
        ),
        migrations.AlterField(
            model_name='services',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Ultima Actualizacion'),
        ),
    ]
