# Generated by Django 4.0.4 on 2022-04-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_options_alter_services_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='info',
            field=models.TextField(verbose_name='Informacion'),
        ),
    ]
