# Generated by Django 4.0.4 on 2022-04-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='public',
            field=models.BooleanField(default=True, verbose_name='¿Visible?'),
        ),
    ]
