# Generated by Django 4.0.4 on 2022-04-28 00:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='info',
            field=ckeditor.fields.RichTextField(verbose_name='Informacion'),
        ),
    ]
