# Generated by Django 4.0.4 on 2022-04-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_services_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='Null', upload_to='services', verbose_name='Imagen'),
        ),
    ]
